# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pablo da Rocha - Primeiro Blog
email: pablodarocha.ribeiro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: pablorochar
github_username:  pablodarocha

# Build settings
markdown: kramdown
highlighter: rouge

# # html minify
# compress_html:
# 	clippings: all 
# 	comments: all 
# 	endings: []
# 	profile: false

# # Links to include in menu navigation
# # For external links add external: true
# links:
#   - title: Home
#     url: /
#   - title: Séries
#     url: /series
#   - title: Tags
#     url: /tags
#   - title: Sobre mim
#     url: /about


# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']